Nombre: DemostraciÃ³n de GitHub Actions
nombre de ejecuciÃ³n: ${{ github.actor }} estÃ¡ probando GitHub Actions ğŸš€
activado: [push]
empleos:
  Explorar-Acciones-de-GitHub:
    Se ejecuta en: ubuntu-latest
    pasos:
      - ejecutar: echo "ğŸ‰ El trabajo se activÃ³ automÃ¡ticamente por un evento ${{ github.event_name }}."
      - ejecutar: echo "ğŸ§ Â¡Este trabajo ahora se estÃ¡ ejecutando en un servidor ${{ runner.os }} alojado en GitHub!"
      - ejecutar: echo "ğŸ” El nombre de tu rama es ${{ github.ref }} y tu repositorio es ${{ github.repository }}."
      - nombre: Consulta el cÃ³digo del repositorio
        Usos: acciones/checkout@v5
      - ejecutar: echo "ğŸ’¡ El repositorio ${{ github.repository }} ha sido clonado en el ejecutor."
      - ejecutar: echo "ğŸ–¥ï¸ El flujo de trabajo ya estÃ¡ listo para probar tu cÃ³digo en el ejecutor."
      - nombre: Lista de archivos en el repositorio
        ejecutar: |
          ls ${{ github.workspace }}
      - ejecutar: echo "ğŸ El estado de este trabajo es ${{ job.status }}."
